this project is aim at providing the medical consultation, medical care and other related services  in real time....
connecting doctors to patient thus reducing consultation time and providing timely care in due time... 
the scope of this project is not limited to providing consultation but other relevant and related medical needs such as ambulance services blood donations etc, 
you are welcome to change add to this project as you see fit inline with medical relevance and other related importance ........
